title: 'President''s Challenge'
title-abbreviated: 'President''s Challenge'
description: 'President''s Challenge. Empowering Lives, Uplifting Communities.'
url: 'https://www.presidentschallenge.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
resources_name: resource-room
favicon: /images/favicon.ico
google_analytics: UA-2833102-27
permalink: none
baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: page
colors:
  primary-color: '#6031b6'
  secondary-color: '#2650AB'
  media-colors:
    - title: media-color-one
      color: '#33566C'
    - title: media-color-two
      color: '#6C4794'
    - title: media-color-three
      color: '#00626B'
    - title: media-color-four
      color: '#00626B'
    - title: media-color-five
      color: '#00626B'staging: https://ncss-pc-staging.netlify.app/
prod: https://ncss-pc-prod.netlify.app/
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
